[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.35"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
hyperevm_testnet = "${HYPEREVM_TESTNET_RPC}"
